# Dependencies
highlighter:      rouge

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

# Permalinks
#permalink:              /:title/
#permalink:              /posts/:categories/:title/
# permalink:            posts/:categories/:year/:month/:day/:title/

# Setup
title:            'Nikunj Rajesh Lad'
name:             'Nikunj Rajesh Lad'
#tagline:          ''
description:      'Computer Vision Developer | Machine Learning Engineer'

seo:
  title:  'Nikunj Rajesh Lad'
  description:  'I love building Computer Vision applications and programming in Python.'
  keywords: 'Computer Vision, Deep Learning, Image Processing'

baseurl:
# blogurl:          /posts/

# Assets
images:         '/img'
pdfs:           '/pdf'

author:
  name:           'Nikunj Rajesh Lad'
  url:            'https://nikunjlad.dev'
  email:          'lad.n@husky.neu.edu'
  github:         'https://github.com/nikunjlad'
  facebook:       'https://www.facebook.com/nikunj.sporty'
  twitter:        'https://twitter.com/LadNikunj'
  googleplus:     ''
  linkedin:       'https://www.linkedin.com/in/nikunjlad '
  resume:         'https://nikunjlad.dev/resume/Nikunj_Lad.pdf'

paginate:         3
# paginate_path:    "/posts/page:num/"

# Custom vars
version:          2.1.0
ipmeta_api_key:   "" # set or use environment variable IPMETA_API_KEY

github:
  repo:           https://github.com/nikunjlad/nikunjlad.github.io

# Collections
collections:
  - publications
  - cvprojects
  - dsprojects
  - experience
  - talks

# defaults:
#   -
#     scope:
#       path: ""
#       type: "cvprojects" # a collection in your site, in plural form
#     values:
#       layout: "default"
